CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');


-- Table structure for table `classification`
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);


-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9,0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Data for table `inventory`

INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES  (
  'Lamborghini',
  'Aventador',
  '2018',
  'Experience the thrill of the Lamborghini Aventador! Powered by a roaring V12 engine, it’s a masterpiece of speed and luxury.',
  '/images/adventador.jpg',
  '/images/adventador-tn.jpg',
  450000,
  62000,
  'Blue',
  2
),
(
  'Batmobile',
  'Custom',
  '2010',
  'Unleash your inner superhero with the iconic Batmobile. Equipped with advanced tech and unmatched agility, it’s built to conquer both traffic and villains.',
  '/images/batmobile.jpg',
  '/images/batmobile-tn.jpg',
  75000,
  35800,
  'Black',
  1
),
(
  'Mystery',
  'Machine',
  '2001',
  'Solve mysteries in style with the iconic Mystery Machine. Equipped with all-wheel drive, it’s ready for any adventure!',
  '/images/mystery-van.jpg',
  '/images/mystery-van-tn.jpg',
  12000,
  135000,
  'Green',
  1
),
(
  'FBI',
  'Surveillance Van',
  '2018',
  'Step into the world of espionage with this upgraded surveillance van. Comes with optional state-of-the-art equipment for an extra $1,500 a month.',
  '/images/survan.jpg',
  '/images/survan-tn.jpg',
  22000,
  16500,
  'Brown',
  1
),
(
  'Chevy',
  'Camaro',
  '2020',
  'Drive in style with this sleek Camaro! Enhanced with modern features and exceptional performance, this car is ready to turn heads wherever you go.',
  '/images/camaro.jpg',
  '/images/camaro-tn.jpg',
  27000,
  85222,
  'Silver',
  2
),
(
  'Dog',
  'Car',
  '2000',
  'Attention dog lovers! This quirky car is a nostalgic gem, complete with fluffy ears and a tail wagging in the rear. Perfect for unique road trips!',
  '/images/dog-car.jpg',
  '/images/dog-car-tn.jpg',
  30000,
  60500,
  'White',
  1
),
(
  'Jeep',
  'Wrangler',
  '2021',
  'Adventure awaits with the Jeep Wrangler! With rugged off-road capabilities and modern tech, this is your ultimate companion for any journey.',
  '/images/wrangler.jpg',
  '/images/wrangler-tn.jpg',
  32000,
  29000,
  'Yellow',
  3
),
(
  'Aerocar International',
  'Aerocar',
  '1965',
  'Escape the gridlock with this rare Aerocar! A seamless transformation from car to plane, it’s your ticket to the skies.',
  '/images/aerocar.jpg',
  '/images/aerocar-tn.jpg',
  800000,
  12000,
  'Red',
  1
),
(
  'Monster',
  'Truck',
  '1998',
  'Dominate the terrain with this colossal Monster Truck. With 60-inch tires and unmatched power, it’s made for thrills and spills.',
  '/images/monster-truck.jpg',
  '/images/monster-truck-tn.jpg',
  180000,
  4500,
  'Purple',
  1
),
(
  'GM',
  'Hummer',
  '2018',
  'Tackle the toughest terrains with the Hummer. This rugged beast offers space, power, and resilience for all your adventures.',
  '/images/hummer.jpg',
  '/images/hummer-tn.jpg',
  62000,
  48000,
  'Yellow',
  4
),
(
  'Mechanic',
  'Special',
  '1967',
  'A hidden gem waiting for some TLC. With a bit of love, this vintage car can become a masterpiece on wheels.',
  '/images/mechanic.jpg',
  '/images/mechanic-tn.jpg',
  500,
  220000,
  'Rust',
  5
),
(
  'Ford',
  'Crown Victoria',
  '2015',
  'Previously used by the police force, this reliable Crown Victoria is now available. Great for daily drives and weekend adventures!',
  '/images/crwn-vic.jpg',
  '/images/crwn-vic-tn.jpg',
  12000,
  115000,
  'White',
  5
),
(
  'Ford',
  'Model T',
  '1925',
  'Own a piece of history! The Ford Model T was the first mass-produced car and a true automotive icon. Perfect for collectors.',
  '/images/model-t.jpg',
  '/images/model-t-tn.jpg',
  35000,
  30000,
  'Black',
  5
),
(
  'Spartan',
  'Fire Truck',
  '2015',
  'Be the hero in emergencies with this Spartan fire truck. Comes equipped with a 1,200-gallon tank and 1,500 ft. of hose.',
  '/images/fire-truck.jpg',
  '/images/fire-truck-tn.jpg',
  55000,
  33000,
  'Red',
  4
),
(
  'Ford',
  'Crown Victoria',
  '2015',
  'Previously used by the police force, this reliable Crown Victoria is now available. Great for daily drives and weekend adventures!',
  '/images/crwn-vic.jpg',
  '/images/crwn-vic-tn.jpg',
  12000,
  115000,
  'White',
  5
),
(
  'Cadillac',
  'Escalade',
  '2022',
  'Luxury redefined! The Cadillac Escalade combines style, comfort, and advanced technology for a premium driving experience.',
  '/images/escalade.jpg',
  '/images/escalade-tn.jpg',
  80000,
  25000,
  'Black',
  4
);
 

-- QUERY 4: Modify the "GM Hummer" record to read "a huge interior" rather than "small interiors" using a single query
UPDATE public.inventory
SET inv_description = REPLACE(
        inv_description,
        'small interiors',
        'a huge interior'
    )
WHERE inv_make = 'GM'
    AND inv_model = 'Hummer';

-- QUERY 6: Update all records in the inventory table to add "/vehicles" to the middle of 
-- the file path in the inv_image and inv_thumbnail columns using a single query
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images', '/images/vehicles'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/images', '/images/vehicles');

-- Message Enchancement
CREATE TABLE IF NOT EXISTS public.message (
	message_id int GENERATED BY DEFAULT AS IDENTITY,
	message_subject character varying NOT NULL,
	message_body text NOT NULL,
	message_created timestamp DEFAULT now() NOT NULL,
	message_to int NOT NULL,
	message_from int NOT NULL,
	message_read boolean DEFAULT false NOT NULL,
	message_archived boolean DEFAULT false NOT NULL,
	CONSTRAINT message_pkey PRIMARY KEY (message_id),
	CONSTRAINT to_fkey FOREIGN KEY (message_to)
    REFERENCES public.account (account_id)
    MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION,
	CONSTRAINT from_fkey FOREIGN KEY (message_from)
    REFERENCES public.account (account_id)
    MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

